anime/urls.py
from django.urls import path, reverse_lazy
from .views import HomePage, HomeAnimes, AnimeDetail, SearchAnime, PlayAnime, ProfileEdit, CreateAccount
from django.contrib.auth import views as auth_view

app_name = 'anime'

urlpatterns = [
    path('', HomePage.as_view(), name='home'),
    path('animes/', HomeAnimes.as_view(), name='animes'),
    path('animes/<int:pk>', AnimeDetail.as_view(), name='details'),
    path('animes/<int:pk>/play/<int:pk2>', PlayAnime.as_view(), name='play'),
    path('animes/search', SearchAnime.as_view(), name = 'search'),
    path('login/', auth_view.LoginView.as_view(template_name='login.html'), name ='login'),
    path('logout/', auth_view.LogoutView.as_view(template_name='logout.html'), name ='logout'),
    path('profile/edit/<int:pk>', ProfileEdit.as_view(), name = 'profileedit'),
    path('profile/edit/password/', auth_view.PasswordChangeView.as_view(template_name='changepass.html', 
                                                                        success_url=reverse_lazy('anime:animes')), name = 'changepass'),
    path('profile/create/', CreateAccount.as_view(), name = 'createaccount'),
]

animeflix/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('anime.urls', namespace='anime')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

anime/models.py
from django.utils import timezone
from django.db import models
from django.contrib.auth.models import AbstractUser

CATEGORY_LIST = (
    ("DRAMA", "Drama"),
    ("SUPERNATURAL", "Supernatural"),
    ("HORROR", "Horror"),
    ("MYSTERY", "Mystery"),
    ("COMEDY", "Comedy"),
    ("ROMANCE", "Romance"),
    ("ACTION", "Action"),
    ("FANTASY", "Fantasy"),
    ("ECCHI", "Ecchi"),
    ("ADVENTURE", "Adventure")
)

# Create your models here.  
class Anime(models.Model):
    title = models.CharField(max_length=150)
    thumb = models.ImageField(upload_to='thumb_animes')
    description = models.TextField(max_length=1000)
    num_views = models.IntegerField(default=0)
    creation_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title
    
class Episode(models.Model):
    anime = models.ForeignKey("Anime", related_name="episodes", on_delete=models.CASCADE)
    title = models.CharField(max_length=150)
    video2 = models.FileField(upload_to="video/%y")
    thumb = models.FileField(upload_to="thumb/%y",blank=True)

    def __str__(self):
        return self.anime.title + " - " + self.title
    
class Categorie(models.Model):
    name = models.ForeignKey(Anime, related_name='category', blank=True, null=True, on_delete=models.DO_NOTHING)
    category = models.CharField(max_length=18, choices=CATEGORY_LIST)
    creation_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.name.title + " - " + self.category
    
class User(AbstractUser):
    watched_movies = models.ManyToManyField("Anime")
    user_image = models.ImageField(upload_to='profile_img', blank=True)

anime/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import User
from django import forms

class FormHome(forms.Form):
    username = forms.CharField(label=False)


class ProfileCreationForm(UserCreationForm):
    email = forms.EmailField()
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

anime/views.py
from django.shortcuts import redirect, reverse
from .models import Anime, Episode, Categorie, User
from .forms import ProfileCreationForm, FormHome
from django.views.generic import TemplateView, ListView, DetailView, FormView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin

class HomePage(FormView):
    template_name = 'homepage.html'
    form_class = FormHome

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('anime:animes')
        else:
            return super().get(request, *args, **kwargs)
        
    def get_success_url(self):
        email = self.request.POST.get('username')
        users_by_email = User.objects.filter(email=email)
        users_by_username = User.objects.filter(username=email)
        if users_by_email or users_by_username:
            return reverse('anime:login')
        else:
            return reverse('anime:createaccount')


class CreateAccount(FormView):
    template_name = 'createaccount.html'
    form_class = ProfileCreationForm

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('anime:login')

class HomeAnimes(LoginRequiredMixin, ListView):
    template_name = 'homeanimes.html'
    model = Anime

class ProfileEdit(LoginRequiredMixin, UpdateView):
    template_name = 'profileedit.html'
    model = User
    fields = ['user_image', 'first_name', 'last_name', 'email']

    def get_success_url(self):
        return reverse('anime:animes')

class AnimeDetail(LoginRequiredMixin, DetailView):
    template_name = 'animedetails.html'
    model = Anime

    def get(self, request, *args, **kwargs):
        anime = self.get_object()
        anime.num_views += 1
        anime.save()
        user = request.user
        user.watched_movies.add(anime)
        user.save()
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(AnimeDetail, self).get_context_data(**kwargs)
        filtered_anime = Anime.objects.filter(id=self.get_object().id)
        related_animes = Categorie.objects.filter(name=self.get_object().id)
        categories = Categorie.objects.all()
        context["related"] = related_animes
        context['current_anime'] = filtered_anime
        context['catnofilter'] = categories
        return context

class PlayAnime(LoginRequiredMixin, DetailView):
    template_name = 'playanime.html'
    model = Anime

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        pk = self.kwargs['pk']
        episodeid = self.kwargs['pk2']
        filtered_anime = Anime.objects.filter(id=pk)
        related_animes = Categorie.objects.filter(name=filtered_anime.first().pk)
        episodelist = Episode.objects.filter(anime=pk)
        context['episode_list'] = episodelist
        context['episodeid'] = episodeid
        context['related'] = related_animes
        context['current_anime'] = filtered_anime
        return context

class SearchAnime(LoginRequiredMixin, ListView):
    template_name = 'searchanime.html'
    model = Anime

    def get_queryset(self):
        search_term = self.request.GET.get('q')
        if search_term:
            object_list = Anime.objects.filter(title__icontains=search_term)
            return object_list
        else:
            None

anime/templates/animedetails.html
{% extends "base.html" %}

{% block title %}AnimeFlix - {{object.title}} {% endblock title %}

{% block content %}
<main class='bg-primary_black min-h-screen w-full'>
    <header class="min-h-screen bg-black bg-opacity-75 bg-blend-overlay showcase border-gray-600 border-b-8 flex justify-center items-center bg-no-repeat">
        <div class="z-10 h-full py-32 md:py-0 text-gray-100 text-center flex items-center flex-col">
            <div class="py-32 w-full flex justify-center">
                <div class="justify-center items-center w-11/12 md:w-10/12">
                    <img class="object-center md:object-center inline w-11/12 md:w-3/12 rounded-md object-cover" src="{{object.thumb.url}}" alt="">
                    <h2 class="md:text-5xl text-4xl font-semibold mb-4">
                        {{object.title}}
                    </h2>
                    <p>{{object.description}}</p>
                </div>
            </div>
        </div>
    </header>

    <div class="flex flex-col justify-center text-center md:text-center p-5 md:p-10">
        {% include "partials/episodes.html" %}
        {% for cat in allcat %}
            {% if cat.first.category in related.first.category %}
                {% include "partials/categories.html" with tag=cat tag2="You Might Like" current_watch=object.pk %}
            {% endif %}
        {% endfor %}
    </div>
</main>
{% endblock content %}

anime/templates/changepass.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}AnimeFlix - Change Password{% endblock title %}
{% block content %}
<header class="min-h-screen bg-black bg-opacity-75 bg-blend-overlay showcase border-gray-600 border-b-8 flex justify-center items-center bg-no-repeat"  style="background-image: url('{% static 'imgs/background-animeflix.gif' %}');">
    <div class="bg-gray-900 bg-opacity-40 py-1 my-2 px-3 z-10 rounded-md h-full py-32 md:py-0 text-gray-100 text-center flex items-center flex-col">
        <form method="post">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Change your Password</legend>
                {{ form|crispy }}
            </fieldset>
            <button class="bg-indigo-700 py-1 my-2 px-3 text-white font-bold md:text-lg rounded-md" type="submit">SUBMIT</button>
        </form>
    </div>
</header>
<footer class=" px-5 py-10 ">
    <ul class="flex justify-between items-center">

        <li>&copy; 2023</li>
        <li> Feito com Python (Django)</li>
        <li>Tiago Martins Andrade</li>
    </ul>
</footer>
{% endblock content %}

anime/templates/homeanimes.html
{% extends "base.html" %}

{% block title %}AnimeFlix - Animes{% endblock title %}

{% block content %}
<main class='bg-primary_black min-h-screen w-full'>
    {% include "partials/categories.html" with tag=recent tag2='NEW' again=True category='new_animes' top=True %}
    {% include "partials/categories.html" with tag=most_watched tag2='MOST WATCHED' again=True category='most_watched' %}
    {% include "partials/categories.html" with tag=request.user.watched_movies.all tag2='CONTINUE WATCHING' again=True category='continue_watching' %}
    {% for cat in allcat %}
        {% include "partials/categories.html" with tag=cat %}
    {% endfor %}
</main>
{% endblock content %}

anime/templates/partials/categories.html
{% if tag.first %}
    <section class='bg-primary_black flex justify-center'>
        {% if top %}
            <div class="pt-20 w-10/12 relative" >
        {% else %}
            <div class="w-10/12 relative" >
        {% endif %}
        {% if tag2 %}
            <h2 class="text-gray-200 text-2xl font-medium">{{tag2}}</h2>
        {% else %}
            <h2 class="text-gray-200 text-2xl font-medium">{{tag.first.category}}</h2>
        {% endif %}
            <div class="wrapper">
                {% if category %}
                    <section id="section1{{category}}" class="flex flex-nowrap items-center justify-center space-x-8 h-4/5 p-10">
                    {% if tag.count > 6 %}
                        <a href="#section2{{category}}" class="arrow__btn text-6xl page">‹</a>
                    {% endif %}
                {% else %}
                    <section id="section1{{tag.first.category}}" class="flex flex-nowrap items-center justify-center space-x-8 h-4/5 p-10">
                    {% if tag.count > 6 %}
                        <a href="#section2{{tag.first.category}}" class="arrow__btn text-6xl page">‹</a>
                    {% endif %}
                {% endif %}
                    {% if again %}
                        {% for category in tag %}
                            {% if forloop.counter < 7 %}
                                <div class="item h-64 m-4">
                                    {% if related.first.pk != category.pk %}
                                        {% if current_watch != category.pk %}
                                            <a href="{% url 'anime:details' category.pk %}">
                                                <img src="{{ category.thumb.url }}" class="rounded-md w-full h-full object-cover">
                                                <h5 class="text-gray-200 text-xs font-medium">{{category.title|wordwrap:30|linebreaksbr}}</h5>
                                            </a>
                                        {% endif %}
                                    {% endif %}
                                </div>
                            {% endif %}
                        {% endfor %}
                    {% else %}
                        {% for category in tag %}
                            {% if forloop.counter < 7 %}
                                <div class="item h-64 m-4">
                                    {% if related.first.pk != category.name.pk %}
                                        {% if current_watch != category.name.pk %}
                                            <a href="{% url 'anime:details' category.name.pk %}">
                                                <img src="{{ category.name.thumb.url }}" class="rounded-md w-full h-full object-cover">
                                                <h5 class="text-gray-200 text-xs font-medium">{{category.title|wordwrap:30|linebreaksbr}}</h5>
                                            </a>
                                        {% endif %}
                                    {% endif %}
                                </div>
                            {% endif %} 
                        {% endfor %}
                    {% endif %}
                    {% if tag.count > 6 %}
                        {% if category %}
                            <a href="#section2{{category}}" class="arrow__btn text-6xl">›</a>
                        {% else %}
                            <a href="#section2{{tag.first.category}}" class="arrow__btn text-6xl">›</a>
                        {% endif %}
                    {% endif %}
                </section>
                {% if category %}
                    <section id="section2{{category}}" class="flex flex-nowrap items-center justify-center space-x-8 h-4/5 p-10">
                        <a href="#section1{{category}}" class="arrow__btn text-6xl">‹</a>
                {% else %}
                    <section id="section2{{tag.first.category}}" class="flex flex-nowrap items-center justify-center space-x-8 h-4/5 p-10">
                        <a href="#section1{{tag.first.category}}" class="arrow__btn text-6xl">‹</a>
                {% endif %}
                    {% if again %}
                        {% for category in tag|slice:"6:" %}
                            {% if forloop.counter < 7 %}
                                <div class="item h-64 m-4">
                                    {% if related.first.pk != category.pk %}
                                        <a href="{% url 'anime:details' category.pk %}">
                                            <img src="{{ category.thumb.url }}" class="rounded-md w-full h-full object-cover">
                                            <h5 class="text-gray-200 text-xs font-medium">{{category.title|wordwrap:30|linebreaksbr}}</h5>
                                        </a>
                                    {% endif %}
                                </div>
                            {% endif %}
                        {% endfor %}
                    {% else %}
                        {% for category in tag|slice:"6:" %}
                                {% if forloop.counter < 7 %}
                                    <div class="item h-64 m-4">
                                        {% if related.first.pk != category.name.pk %}
                                            <a href="{% url 'anime:details' category.name.pk %}">
                                                <img src="{{ category.name.thumb.url }}" class="rounded-md w-full h-full object-cover">
                                                <h5 class="text-gray-200 text-xs font-medium">{{category.name.title|wordwrap:30|linebreaksbr}}</h5>
                                            </a>
                                        {% endif %}
                                    </div>
                                {% endif %}
                        {% endfor %}
                    {% endif %}
                    {% if tag.count > 6 %}
                        {% if category %}
                            <a href="#section1{{category}}" class="arrow__btn text-6xl">›</a>
                        {% else %}
                            <a href="#section1{{tag.first.category}}" class="arrow__btn text-6xl">›</a>
                        {% endif %}
                    {% endif %}
                </section>
            </div>
        </div>
    </section>
{% endif %}

anime/templates/partials/episodes.html
{% if object.episodes.all.count > 0 %}
    <section class='bg-primary_black flex justify-center'>
        <div class="w-10/12 relative" >
            <h2 class="px-48 md:text-5xl text-4xl font-semibold mb-4">Episodes</h2>
            <div class="wrapper">
                <section id="section1episode" class="flex flex-nowrap items-center justify-center space-x-8 h-4/5 p-10">
                    {% if object.episodes.all.count > 5 %}
                        <a href="#section2episode" class="arrow__btn text-6xl page">‹</a>
                    {% endif %}
                    {% for episode in object.episodes.all %}
                        {% if forloop.counter < 6 %}
                            <div class="item h-64 m-4">
                                <a href="{% url 'anime:play' object.pk episode.pk %}">
                                    <img src="{{ episode.thumb.url }}" class="rounded-md w-full h-full object-cover">
                                    <h5 class="text-gray-200 text-xs font-medium">{{episode.title|wordwrap:30|linebreaksbr}}</h5>
                                </a>
                            </div>
                        {% endif %}
                    {% endfor %}
                    {% if object.episodes.all.count > 5 %}
                        <a href="#section2episode" class="arrow__btn text-6xl">›</a>
                    {% endif %}
                </section>
                {% if object.episodes.all|length > 5 %}
                    <section id="section2episode" class="flex flex-nowrap items-center justify-center space-x-8 h-4/5 p-10">
                        {% if object.episodes.all.count > 5 %}
                            <a href="#section1episode" class="arrow__btn text-6xl">‹</a>
                        {% endif %}
                        {% for episode in object.episodes.all %}
                            {% if forloop.counter > 5 %}
                                <div class="item h-64 m-4">
                                    <a href="{% url 'anime:play' object.pk episode.pk %}">
                                        <img src="{{ episode.thumb.url }}" class="rounded-md w-full h-full object-cover">
                                        <h5 class="text-gray-200 text-xs font-medium">{{episode.title|wordwrap:30|linebreaksbr}}</h5>
                                    </a>
                                </div>
                            {% endif %}
                        {% endfor %}
                        {% if object.episodes.all.count > 5 %}
                            <a href="#section1episode" class="arrow__btn text-6xl">›</a>
                        {% endif %}
                    </section>
                {% endif %}
            </div>
        </div>
    </section>
{% endif %}

anime/templates/partials/related.html
<section class='bg-primary_black flex justify-center'>
    <div class="w-10/12 relative">
        <h2 class="px-48 md:text-5xl text-4xl font-semibold mb-4 text-center">You might like</h2>
        <div class="wrapper">
            <section id="section1related" class="flex flex-nowrap items-center justify-center space-x-8 h-4/5 p-10">
                <a href="#section2related" class="arrow__btn text-6xl page">‹</a>
                {% for category in related|slice:1 %}
                    {% for anime in category.category %}
                        {% if forloop.counter < 8 %}
                            <div class="item h-64 m-4">
                                {% if anime.pk != current_anime.first.pk %}
                                    <a href="{% url 'anime:details' anime.pk %}">
                                        <img src="{{ anime.thumb.url }}" class="rounded-md w-full h-full object-cover">
                                        <h5 class="text-gray-200 text-xs font-medium">{{anime.title|wordwrap:30|linebreaksbr}}</h5>
                                    </a>
                                {% endif %}
                            </div>
                        {% endif %}
                    {% endfor %}
                {% endfor %}
                <a href="#section2related" class="arrow__btn text-6xl">›</a>
            </section>
            <section id="section2related" class="flex flex-nowrap items-center justify-center space-x-8 h-4/5 p-10">
                <a href="#section1related" class="arrow__btn text-6xl">‹</a>
                {% for category in related|slice:1 %}
                    {% for anime in anime_list|slice:"7:" %}
                        {% if forloop.counter < 8 %}
                            {% if anime.pk != current_anime.first.pk %}
                                <div class="item h-64 m-4">
                                    <a href="{% url 'anime:details' anime.pk %}">
                                        <img src="{{ anime.thumb.url }}" class="rounded-md w-full h-full object-cover">
                                        <h5 class="text-gray-200 text-xs font-medium">{{anime.title|wordwrap:30|linebreaksbr}}</h5>
                                    </a>
                                </div>
                            {% endif %}
                        {% endif %}
                    {% endfor %}
                {% endfor %}
                <a href="#section1related" class="arrow__btn text-6xl">›</a>
            </section>
        </div>
    </div>
</section>

anime/templates/playanime.html
{% extends "base.html" %}
{% load embed_video_tags %}

{% block title %}AnimeFlix - {{object.title}} {% endblock title %}

{% block content %}
<header class="min-h-screen bg-black bg-opacity-75 bg-blend-overlay showcase border-gray-600 border-b-8 flex justify-center items-center bg-no-repeat">
    <div class="z-10 h-full py-32 md:py-0 text-gray-100 text-center flex items-center flex-col">
        <div class="w-full flex justify-center">
            <div class="flex justify-center items-center w-11/12 md:w-10/12">
                <video
                    id="my-video"
                    class="video-js"
                    controls
                    preload="auto"
                    width="w-full"
                    height="h-full"
                    data-setup='{}'
                >
                    {% for episode in episode_list %}
                        {% if episode.pk == episodeid%}
                            <source src="{{episode.video2.url}}" type="video/mp4" />
                        {% endif %}
                    {% endfor %}
                </video>
            </div>
        </div>
    </div>
</header>
<section class='bg-primary_black flex justify-center'>
    <div class="w-10/12 relative" >
        <h2 class="px-48 md:text-5xl text-4xl font-semibold mb-4">Episodes</h2>
        <div class="wrapper">
        <section id="section1episode" class="flex flex-nowrap items-center justify-center space-x-8 h-4/5 p-10">
            <a href="#section2episode" class="arrow__btn text-6xl page">‹</a>
            {% for episode in episode_list %}
                {% if forloop.counter < 6 %}
                    <div class="item h-64 m-4">
                        <a href="{% url 'anime:play' current_anime.first.pk episode.pk %}">
                            <img src="{{ episode.thumb.url }}" class="rounded-md w-full h-full object-cover">
                            <h5 class="text-gray-200 text-xs font-medium">{{episode.title|wordwrap:30|linebreaksbr}}</h5>
                        </a>
                    </div>
                {% endif %}
            {% endfor %}
                <a href="#section2episode" class="arrow__btn text-6xl">›</a>
        </section>
            {% if episode_list.all|length > 5 %}
            <section id="section2episode" class="flex flex-nowrap items-center justify-center space-x-8 h-4/5 p-10">
                <a href="#section1episode" class="arrow__btn text-6xl">‹</a>
                {% for episode in episode_list %}
                    {% if forloop.counter > 5 %}
                        <div class="item h-64 m-4">
                            <a href="{% url 'anime:play' current_anime.first.pk episode.pk %}">
                                <img src="{{ episode.thumb.url }}" class="rounded-md w-full h-full object-cover">
                                <h5 class="text-gray-200 text-xs font-medium">{{episode.title|wordwrap:30|linebreaksbr}}</h5>
                            </a>
                        </div>
                    {% endif %}
                {% endfor %}
                <a href="#section1episode" class="arrow__btn text-6xl">›</a>
            </section>
            {% endif %}
        </div>
    </div>
</section>
{% for cat in allcat %}
    {% if cat.first.category in related.first.category %}
        {% include "partials/categories.html" with tag=cat tag2="You Might Like" %}
    {% endif %}
{% endfor %}
<script src="https://vjs.zencdn.net/8.5.2/video.min.js"></script>
{% endblock content %}

anime/templates/profileedit.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}AnimeFlix - Profile Edit{% endblock title %}

{% block head %}
<style>
    #id_user_image{
        width: 200%;
        align-self: center;
    }
    #id_first_name, #id_email, #id_last_name {
        background-color: slategray;
        color: white;
        padding: 5px 5px;
    }
</style>
{% endblock head %}
{% block content %}
<header class="min-h-screen bg-black bg-opacity-75 bg-blend-overlay showcase border-gray-600 border-b-8 flex justify-center items-center bg-no-repeat"  style="background-image: url('{% static 'imgs/background-animeflix.gif' %}');">
    <div class="bg-gray-900 bg-opacity-40 py-1 my-2 px-3 z-10 rounded-md h-full py-32 md:py-0 text-gray-100 text-center flex items-center flex-col">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Profile Edit</legend>
                <div class="flex flex-row w-96">
                    <div class="md:w-5/12 flex flex-col text-center md:text-left p-5 md:p-10 flex-none">
                        {% if not user.user_image %}
                            <img src="{% static 'imgs/default_user_img.png' %}" class="w-14 h-14" alt="">
                            {{form.user_image}}
                        {% else %}
                            <img src="{{ user.user_image.url }}" class="w-14 h-14" alt="">
                        {% endif %}
                    </div>
                    <div class='md:w-6/12 flex flex-col justify-center text-center md:text-left p-2 md:p-2 flex-initial w-64'>
                       <div class="justify-center items-center flex flex-col self-start">
                            {{ user.username }}
                            <h5 class='pt-6'>First Name<h5>
                            {{form.first_name}}
                            <h5 class='pt-6'>Last Name<h5>
                            {{form.last_name}}
                            <h5 class='pt-6'>E-mail<h5>
                            {{form.email}}
                       </div> 
                    </div>
                </div>
            </fieldset>
            <small><p class="mt-6"><a href="{% url 'anime:changepass' %}">Need to change your password?</a></p></small>
            <button class="mt-6 bg-indigo-700 py-1 px-3 text-white font-bold md:text-lg rounded-md" type="submit">SAVE</button>
            <a href="{% url 'anime:animes' %}">
                <button class="bg-indigo-700 py-1 my-2 px-3 text-white font-bold md:text-lg rounded-md">
                    CANCEL
                </button>
            </a>
            <a href="{% url 'anime:animes' %}">
                <button class="bg-indigo-700 py-1 my-2 px-3 text-white font-bold md:text-lg rounded-md">
                    DELETE PROFILE
                </button>
            </a>
        </form>
    </div>
</header>
<footer class=" px-5 py-10 ">
    <ul class="flex justify-between items-center">

        <li>&copy; 2023</li>
        <li> Feito com Python (Django)</li>
        <li>Tiago Martins Andrade</li>
    </ul>
</footer>
{% endblock content %}

anime/templates/searchanime.html
{% extends "base.html" %}

{% block title %}Anime Search{% endblock title %}

{% block content %}
<main class='bg-primary_black min-h-screen w-full'>
    <section class='bg-primary_black  min-h-screen flex justify-center py-10'>
        <div class="p-8 w-10/12 relative" >
            <h2 class="text-gray-200 text-2xl font-medium">
                Search Results
            </h2>
            <div class="flex flex-wrap items-center min-w-full movie_lis">
              {% for anime in object_list %}
                <div class="m-4 bg-blue-500 flex-shrink-0 rounded-md cursor-pointer h-64 w-96">
                    <a href="{% url 'anime:details' anime.pk %}">
                      <img src="{{ anime.thumb.url }}" class="object-cover w-full h-full " alt="">
                    </a>
                    <h5 class="text-gray-200 text-xs font-medium">{{anime.title|wordwrap:30|linebreaksbr}}</h5>
                </div>
              {% endfor %}
            </div>


        </div>
    </section>
</main>
{% endblock content %}

templates/navbar.html
{% load static %}
<nav class="w-full flex justify-between items-center py-3 px-4 fixed z-50">
    <div class="w-6/12">
        <a href="/">
            <img src="{% static "imgs/animeflix.png" %}" alt="AnimeflixLogo" class="w-2/12">
        </a>
    </div>
    <div class="w-6/12 flex flex-nowrap justify-end">
        {% if user.is_authenticated %}
            <div class="mr-2">
                <form method="GET" action="{% url 'anime:search' %}">
                    <input type="text" class="py-1 px-2 rounded-md text-black" name="q" value="{{request.GET.q}}" placeholder="Search...">
                    <input type="submit" value="">
                </form>
            </div>
            <div class="mr-2">
                <a href="{% url 'anime:logout' %}?next=/">
                    <button class="bg-indigo-700 text-white py-1 px-3 rounded-md">
                        Logout
                    </button>
                </a>
            </div>
            <div class="mr-2">
                <a href="{% url 'anime:profileedit' user.pk %}">
                    {% if user.user_image %}
                        <img src="{{ user.user_image.url }}" class='w-8 h-8' alt="">
                    {% else %}
                        <img src="{% static 'imgs/default_user_img.png' %}" class='w-8 h-8' alt="">
                    {% endif %}
                </a>
            </div>
        {% else %}
            <div class="mr-2">
                <a href="{% url 'anime:login' %}">
                    <button class="bg-indigo-700 text-white py-1 px-3 rounded-md">
                        Login
                    </button>
                </a>
            </div>
        {% endif %}
    </div>
</nav>